// Zero-dependency token build: tokens.json -> dist/tokens.{css,scss,js,d.ts}
// Run: npm run build  (or: node build.mjs)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const here = (p) => new URL(p, import.meta.url);
const t = JSON.parse(readFileSync(here('./tokens.json'), 'utf8'));
const P = '--sb';

const colorLight = [];
const colorDark = [];
for (const [name, v] of Object.entries(t.color)) {
  colorLight.push(`  ${P}-${name}: ${v.light};`);
  colorDark.push(`  ${P}-${name}: ${v.dark};`);
}

const radius = Object.entries(t.radius).map(([k, v]) => `  ${P}-radius-${k}: ${v};`);

const shadowLight = Object.entries(t.shadow).map(([k, v]) => `  ${P}-shadow-${k}: ${v.light};`);
const shadowDark = Object.entries(t.shadow).map(([k, v]) => `  ${P}-shadow-${k}: ${v.dark};`);

const font = [
  `  ${P}-font-ui: ${t.font.ui};`,
  `  ${P}-font-mono: ${t.font.mono};`,
];
for (const [k, v] of Object.entries(t.font.scale)) {
  font.push(`  ${P}-type-${k}-size: ${v.size};`);
  font.push(`  ${P}-type-${k}-weight: ${v.weight};`);
}

const header = `/* brand-tokens v${t.$version} — GENERATED by build.mjs. Do not edit by hand; edit tokens.json. */`;

const css = `${header}
:root {
  /* color */
${colorLight.join('\n')}

  /* radius */
${radius.join('\n')}

  /* shadow */
${shadowLight.join('\n')}

  /* typography */
${font.join('\n')}
}

[data-theme="dark"] {
  /* color */
${colorDark.join('\n')}

  /* shadow */
${shadowDark.join('\n')}
}
`;

mkdirSync(here('./dist/'), { recursive: true });
writeFileSync(here('./dist/tokens.css'), css);
// CSS custom properties are valid SCSS, so consumers can @use/@import either file.
writeFileSync(here('./dist/tokens.scss'), css);

// JS + d.ts: token() references + raw light/dark hex maps for JS-driven styling.
const ref = {}, light = {}, dark = {};
for (const [name, v] of Object.entries(t.color)) {
  ref[name] = `var(${P}-${name})`;
  light[name] = v.light;
  dark[name] = v.dark;
}
writeFileSync(here('./dist/tokens.js'), `// brand-tokens v${t.$version} — GENERATED by build.mjs. Do not edit by hand.
export const version = ${JSON.stringify(t.$version)};
export const token = ${JSON.stringify(ref, null, 2)};
export const lightValues = ${JSON.stringify(light, null, 2)};
export const darkValues = ${JSON.stringify(dark, null, 2)};
`);

writeFileSync(here('./dist/tokens.d.ts'), `// brand-tokens v${t.$version} — GENERATED by build.mjs. Do not edit by hand.
export declare const version: string;
export type TokenName = ${Object.keys(ref).map((k) => `'${k}'`).join(' | ')};
export declare const token: Record<TokenName, string>;
export declare const lightValues: Record<TokenName, string>;
export declare const darkValues: Record<TokenName, string>;
`);

console.log(`Built dist/tokens.{css,scss,js,d.ts} from ${Object.keys(t.color).length} colors (v${t.$version}).`);
